### ISSUE TITLE
Input file

### ISSUE THREAD

**Issue by samcro1967** [jwater7/docker-godaddy-publicip-updater#1]
Is there anyway to pass the API key, secret, a names, etc. in via an input file?  Right now to add an a name, I am removing the container, updating the create command, and recreating.  Thinking it would be easier to have an input file that could be updated and the container restarted.

**Comment by jwater7** [comment]
I don't use godaddy anymore and don't have an account with them so I can't test this, but I pushed a fix that should let you use a config file for defaults instead of environment variables.  See the README for more info.

**Comment by jwater7** [comment]
BTW, if this works - let me know and I can tag it as a new release - right now, it's just on master/latest.  Otherwise if it doesn't, I'm always open to Pull Requests for follow-on fixes, thanks

**Comment by samcro1967** [comment]
Thanks for taking a look at this.  The container is not seeing the json file I am passing it.  The path is correct.  I copied and pasted it to ensure no typos.  The docker logs are below.

**Here is the command I used to create the container:**
docker create --name=fix1 -e UPDATER_CONFIG_FILE=C:\Users\username\Documents\Docker\updategodaddy\UPDATER_CONFIG_FILE.json fix1

I also wanted to make sure I understood the input file format as I am not a json expert.

**JSON file example**
{"GODADDY_API_KEY": "key1"}
{"GODADDY_API_SECRET": "secret1"}
{"GODADDY_DOMAINS": "domain1.net"}
{"GODADDY_A_NAMES": "aname1,aname2,aname3"}
**Docker logs**
C:\Users\username\Downloads\docker-godaddy-publicip-updater-fixes-1>docker logs fix1
2020-04-28 11:20:17,268 : ERROR : root - No default config found, continuing.
Traceback (most recent call last):
  File "/godaddy-publicip-updater.py", line 34, in <module>
    with open(config_file) as config_file_data:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\Documents\\Docker\\updategodaddy\\UPDATER_CONFIG_FILE.json'
Traceback (most recent call last):
  File "/godaddy-publicip-updater.py", line 53, in <module>
    godaddy_api_key = get_config_value('GODADDY_API_KEY')
  File "/godaddy-publicip-updater.py", line 47, in get_config_value
    return os.environ[key]
  File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'GODADDY_API_KEY'
2020-04-28 11:20:18,575 : ERROR : root - No default config found, continuing.
Traceback (most recent call last):
  File "/godaddy-publicip-updater.py", line 34, in <module>
    with open(config_file) as config_file_data:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\Documents\\Docker\\updategodaddy\\UPDATER_CONFIG_FILE.json'
Traceback (most recent call last):
  File "/godaddy-publicip-updater.py", line 53, in <module>
    godaddy_api_key = get_config_value('GODADDY_API_KEY')
  File "/godaddy-publicip-updater.py", line 47, in get_config_value
    return os.environ[key]
  File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'GODADDY_API_KEY'

**Comment by jwater7** [comment]
Thanks for taking a look.  I’m not too familiar with windows paths in docker, but because this is a Linux container, my hunch is the mounted path isn’t working with it.  Try mounting the volume to a Linux path and then pass in that path with the environment variable.  E.g.:
-v “C:\Users\username\Documents\Docker\updategodaddy\UPDATER_CONFIG_FILE.json:/config.json”
-e “ UPDATER_CONFIG_FILE=/config.json”

Your json file format will also need to change slightly, something more like (bracing at beginning and end, commas separate props):
{"GODADDY_API_KEY": "key1",
"GODADDY_API_SECRET": "secret1",
"GODADDY_DOMAINS": "domain1.net",
"GODADDY_A_NAMES": "aname1,aname2,aname3"}

Hope this helps.  I’ll do a little research for my own understanding on windows paths too.

**Comment by samcro1967** [comment]
That appears to have worked.  Thanks!  This will make it easier to maintain.

C:\Windows\system32>docker logs fix1
2020-04-28 17:36:10,948 : INFO : root - new-ip: #.#.#.#, old-ip: False
